### ISSUE TITLE
Are we going to use Redux?

### ISSUE THREAD

**Issue by DrCopernicus** [csecapstone485organization/ddf-mobile#4]
Probably not, but I'll leave that up to Julian (if time is willing).

**Comment by nao-de** [comment]
I've created a Redux branch using boilerplate code from this project: https://github.com/LeoLeBras/react-native-redux-starter-kit/tree/next

I'm working on converting our existing code to Redux-style components and will submit a pull request with explanations so that we can develop future components in Redux.
